export const AUTH_SESSION = "AUTH_SESSION";

export const USER_LIST = "USER_LIST";

export const APPLICATION_LIST = "APPLICATION_LIST";

export const ROLE_LIST = "ROLE_LIST";

export const ROLE_PERMISSION_LIST = "ROLE_PERMISSION_LIST";

export const AUDIT_LOG_LIST = "AUDIT_LOG_LIST";

export const MAIL_AUDIT_LOG_LIST = "MAIL_AUDIT_LOG_LIST";
export const SCHEDULED_EMAIL_LIST = "SCHEDULED_EMAIL_LIST";
export const EMAIL_TEMPLATE_LIST = "EMAIL_TEMPLATE_LIST";
export const MAIL_CLIENT_APPLICATION_LIST = "MAIL_CLIENT_APPLICATION_LIST";
